#:schema ../../node_modules/wrangler/config-schema.json

name = "bobot-spirit"
main = "build/index.js"
compatibility_date = "2026-05-02"
workers_dev = false
preview_urls = false

[build]
command = "cargo install worker-build && worker-build --profile=wasm-release --panic-unwind"

[[routes]]
zone_name = "saplyn.site"
pattern = "spirit.bobo.saplyn.site"
custom_domain = true

[observability.logs]
enabled = true
invocation_logs = false
head_sampling_rate = 1.00

[observability.traces]
enabled = true
head_sampling_rate = 1.00

[[secrets_store_secrets]]
binding = "QQ_BOT_ID"
store_id = "7afbc0c2179847f893ba21721f5d8df4"
secret_name = "QQ_BOT_ID"

[[secrets_store_secrets]]
binding = "QQ_BOT_SECRET"
store_id = "7afbc0c2179847f893ba21721f5d8df4"
secret_name = "QQ_BOT_SECRET"
