#:schema ../../node_modules/wrangler/config-schema.json

name = "bobot"
main = "build/index.js"
compatibility_date = "2026-04-12"

[build]
command = "cargo install worker-build && worker-build --profile=wasm-release --panic-unwind"

[secrets]
required = ["QQ_BOT_ID", "QQ_BOT_SECRET", "QQ_OAUTH_ID", "QQ_OAUTH_SECRET"]

[[hyperdrive]]
binding = "BOBOT_STORAGE"
id = "29ab74ac8c904d0585d58668438de721"
localConnectionString = "postgresql://postgres:postgres@127.0.0.1:54322/postgres"

[[d1_databases]]
binding = "BOBOT_STATEFUL"
database_name = "bobot-stateful"
database_id = "39a165b6-ca4d-4837-81ef-e312a4d05b4c"
migrations_dir = "../stateful/"

[triggers]
crons = ["0 */2 * * *"]

[[routes]]
zone_name = "saplyn.site"
pattern = "bobot.saplyn.site"
custom_domain = true

[observability.logs]
enabled = true
invocation_logs = false
head_sampling_rate = 1.00

[observability.traces]
enabled = true
head_sampling_rate = 1.00
