#:schema ../../node_modules/wrangler/config-schema.json

name = "bobot"
main = "build/index.js"
compatibility_date = "2026-04-12"

[build]
command = "cargo install worker-build && worker-build --release --panic-unwind"

[secrets]
required = ["QQBOT_ID", "QQBOT_SECRET"]

[[routes]]
pattern = "bobot.saplyn.site"
custom_domain = true

[observability.logs]
enabled = true
head_sampling_rate = 1.00
