name: Laboratory

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/dev-laboratory.yml
    branches:
      - dev

env:
  PROJECT_DIR: bobot/spirit/

jobs:
  laboratory:
    name: Laboratory
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: laboratory
      url: ${{ steps.domain.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get OAuth domain
        id: domain
        working-directory: bobot/oauth/
        run: echo "url=https://$(pipx run tomlq '.routes[] | select(.custom_domain == true) | .pattern' wrangler.toml -r)" >> $GITHUB_OUTPUT

      - name: Check OAuth domain
        run: echo ${{ steps.domain.outputs.url }}
