name: Build Bobot Online

on:
  workflow_dispatch:
  push:
    paths:
      - bobot/online/**
      - package.json
      - bun.lock
    branches:
      - dev

env:
  PROJECT_DIR: bobot/online/

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Build application
        run: bun run build --preset github_pages
        working-directory: ${{ env.PROJECT_DIR }}
        env:
          NUXT_PUBLIC_SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          NUXT_PUBLIC_SUPABASE_KEY: ${{ vars.SUPABASE_KEY }}
