name: Dependency audit

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  bun-audit:
    name: Bun audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Bun audit
        run: bun audit --audit-level=high

  bun-outdated:
    name: Bun outdated check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Bun outdated check
        run: bun outdated

  cargo-audit:
    name: Cargo audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup `cargo-binstall`
        uses: cargo-bins/cargo-binstall@main

      - name: Setup `cargo-audit`
        run: cargo-binstall cargo-audit --no-confirm

      - name: Cargo audit
        run: cargo audit --deny warnings

  cargo-outdated:
    name: Cargo outdated check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup `cargo-binstall`
        uses: cargo-bins/cargo-binstall@main

      - name: Setup `cargo-outdated`
        run: cargo-binstall cargo-outdated --no-confirm

      - name: Cargo outdated check
        run: cargo outdated
